sudo: false

language: php

php:
  - 7.4

before_install:
  - sudo pip install codecov

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - phpenv rehash

script:
  - vendor/bin/phpunit --verbose --colors --coverage-clover=coverage.xml

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.composer/cache

after_success:
  - bash <(curl -s https://codecov.io/bash)
